name: Jira Issue Auto-Transition

on:
  push:
    branches:
      - dev
      - main

jobs:
  jira-transition:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pando-develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Jira issue key
        id: find_issue
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.event.head_commit.message }}
          from: commits

      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Transition Jira issue
        uses: atlassian/gajira-transition@v3
        if: steps.find_issue.outputs.issueKeys != ''
        with:
          issue: ${{ steps.find_issue.outputs.issueKeys }}
          transition: ${{ github.ref == 'refs/heads/dev' && 'QA' || 'Done' }}
