name: Create Jira Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pando-develop'

    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: GOOD
          issuetype: Task
          summary: "[GH] ${{ github.event.issue.title }}"
          description: |
            ▶ 작성자: ${{ github.event.issue.user.login }}
            ▶ URL: ${{ github.event.issue.html_url }}

            — 이슈 본문 —
            ${{ github.event.issue.body }}
